services:
  eventflow.api:
    image: ${DOCKER_REGISTRY-}eventflowapi
    container_name: EventFlow.api
    build:
      context: .
      dockerfile: src/API/EventFlow.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  eventflow.database:
    image: postgres:17
    container_name: EventFlow.Database
    environment:
      POSTGRES_DB: eventflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  eventflow.seq:
    image: datalust/seq:2024.3 # or latest
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341
