//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventFlow.Modules.Attendance.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddBsonGuidRepresentation_EventId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
