name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: "10.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore EventFlow.slnx

      - name: Build
        run: dotnet build EventFlow.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test EventFlow.slnx --configuration Release --no-build

      - name: Publish
        run: dotnet publish src/API/EventFlow.Api/EventFlow.Api.csproj --configuration Release --no-build